### ISSUE TITLE
Kernel crashes while enabling target mode on NPIV ports

### ISSUE THREAD

**Issue by ArianWeber** [SCST-project/scst#56] opened 2022-06-05 10:56 UTC
Hi, first of all I want to thank you for the amazing work you are doing on the SCST project!

We are experiencing kernel crashes shortly after enabling target mode on a FibreChannel NPIV port using the new `qla2x00t-32gbit` driver. Stacktraces of the crashes mostly indicate a page fault in the function `qlt_find_sess_invalidate_other` within `qla2x00t-32gbit/qla_target.c`. However there also were occasions where the page fault occurred in `qlt_handle_login` or `qlt_logo_completion_handler`.

We did already test multiple releases of SCST (3.2, 3.5 & 3.6) as well as the current master branch (as of commit f7fabfd200).
We also tried multiple levels of debug output (e.g with `2debug` and `ql2xextended_error_logging`) and two types of FC cards (see below). All versions were susceptible to the crashes.

### Steps to reproduce:
- Enable target mode on parent hardware port
- Create NPIV port
- Enable target mode on NPIV port

### Our System
We are using a custom gentoo-based distribution with linux kernel version 5.4.109 and install that exact OS image to multiple machines with two types of FibreChannel Cards:
1. ISP2722-based 16/32Gb Fibre Channel to PCIe Adapter (QLE2692, ISP2722)
2. ISP2532-based 8Gb Fibre Channel to PCI Express HBA (QLE2562, ISP2532)

Each machine is connected to two initiators using a FibreChannel switch.

### Stacktraces:
```
PID: 0      TASK: ffff88846bd97000  CPU: 7   COMMAND: "swapper/7"
 #0 [ffffc90000234bb0] machine_kexec at ffffffff810865ff
 #1 [ffffc90000234bf8] __crash_kexec at ffffffff8110c8e7
 #2 [ffffc90000234cc0] crash_kexec at ffffffff8110d5f0
 #3 [ffffc90000234cd0] oops_end at ffffffff810651fc
 #4 [ffffc90000234cf0] page_fault at ffffffff81e0102f
    [exception RIP: qlt_find_sess_invalidate_other+433]
    RIP: ffffffffa011902f  RSP: ffffc90000234da8  RFLAGS: 00010007
    RAX: ffffffffffffff90  RBX: ffff88845d680003  RCX: 0000000000000000
    RDX: 0000000000000000  RSI: 0000000000000046  RDI: ffff88845a6e79b0
    RBP: ffff88845a6e7598   R8: 0000000000000001   R9: 0000000000000003
    R10: ffff88845a6e7598  R11: 000000000000f026  R12: 0000000000010100
    R13: ffff88845d182d00  R14: 21000024ff3e2e75  R15: ffff88845a6e79c0
    ORIG_RAX: ffffffffffffffff  CS: 0010  SS: 0018
 #5 [ffffc90000234df8] qlt_find_sess_invalidate_other at ffffffffa0119cf3 [qla2xxx_scst]
 #6 [ffffc90000234e68] qlt_find_sess_invalidate_other at ffffffffa011a5c9 [qla2xxx_scst]
 #7 [ffffc90000234eb8] qlt_24xx_process_atio_queue at ffffffffa011c10b [qla2xxx_scst]
 #8 [ffffc90000234f10] qla83xx_msix_atio_q at ffffffffa011c818 [qla2xxx_scst]
 #9 [ffffc90000234f30] __handle_irq_event_percpu at ffffffff810e2460
#10 [ffffc90000234f70] handle_irq_event_percpu at ffffffff810e2565
#11 [ffffc90000234f98] handle_irq_event at ffffffff810e25cb
#12 [ffffc90000234fb0] handle_edge_irq at ffffffff810e5eb6
#13 [ffffc90000234fc8] do_IRQ at ffffffff81e01824
--- <IRQ stack> ---
#14 [ffffc900000ffde8] ret_from_intr at ffffffff81e00a0f
    [exception RIP: cpuidle_enter_state+237]
    RIP: ffffffff81a959dc  RSP: ffffc900000ffe90  RFLAGS: 00000202
    RAX: ffff88847fde7600  RBX: ffff88846a6f0800  RCX: 000000000000001f
    RDX: 0000000000000000  RSI: 0000000000000007  RDI: 0000000000000000
    RBP: ffffffff828db1c0   R8: 0000005908d6505f   R9: ffff88847fddc8e0
    R10: 071c71c71c71c71c  R11: 0000000000000020  R12: 0000000000000002
    R13: 00000059079d3dd0  R14: 0000005908d6505f  R15: 0000000000000000
    ORIG_RAX: ffffffffffffffdb  CS: 0010  SS: 0018
#15 [ffffc900000ffec0] cpuidle_enter at ffffffff81a95b0b
#16 [ffffc900000ffee0] do_idle at ffffffff810cc2bf
#17 [ffffc900000fff20] cpu_startup_entry at ffffffff810cc465
#18 [ffffc900000fff30] start_secondary at ffffffff81080654
#19 [ffffc900000fff50] secondary_startup_64 at ffffffff810000d4

---

PID: 0      TASK: ffff88846dd94600  CPU: 4   COMMAND: "swapper/4"
 #0 [ffffc900001b0bc0] machine_kexec at ffffffff810865ff
 #1 [ffffc900001b0c08] __crash_kexec at ffffffff8110c8e7
 #2 [ffffc900001b0cd0] crash_kexec at ffffffff8110d5f0
 #3 [ffffc900001b0ce0] oops_end at ffffffff810651fc
 #4 [ffffc900001b0d00] page_fault at ffffffff81e0102f
    [exception RIP: qlt_logo_completion_handler+305]
    RIP: ffffffffa00a1b24  RSP: ffffc900001b0db0  RFLAGS: 00010013
    RAX: ffffffffffffff90  RBX: ffff88828ea80003  RCX: 0000000000000000
    RDX: 0000000000000000  RSI: 0000000000000046  RDI: ffff888354b7d958
    RBP: ffff888354b7d598   R8: 0000000000000001   R9: 0000000000000003
    R10: 000000000001fb89  R11: 0000000000000090  R12: 0000000000010000
    R13: 21000024ff3e2e75  R14: ffff88845ae80380  R15: ffff888354b7d968
    ORIG_RAX: ffffffffffffffff  CS: 0010  SS: 0018
 #5 [ffffc900001b0df8] qlt_logo_completion_handler at ffffffffa00a2662 [qla2xxx_scst]
 #6 [ffffc900001b0e68] qlt_logo_completion_handler at ffffffffa00a2efb [qla2xxx_scst]
 #7 [ffffc900001b0eb8] qlt_24xx_process_atio_queue at ffffffffa00a94b6 [qla2xxx_scst]
 #8 [ffffc900001b0f10] qla83xx_msix_atio_q at ffffffffa00a96d0 [qla2xxx_scst]
 #9 [ffffc900001b0f30] __handle_irq_event_percpu at ffffffff810e2460
#10 [ffffc900001b0f70] handle_irq_event_percpu at ffffffff810e2565
#11 [ffffc900001b0f98] handle_irq_event at ffffffff810e25cb
#12 [ffffc900001b0fb0] handle_edge_irq at ffffffff810e5eb6
#13 [ffffc900001b0fc8] do_IRQ at ffffffff81e01824
--- <IRQ stack> ---
#14 [ffffc900000e7de8] ret_from_intr at ffffffff81e00a0f
    [exception RIP: cpuidle_enter_state+237]
    RIP: ffffffff81a95f3c  RSP: ffffc900000e7e90  RFLAGS: 00000202
    RAX: ffff88846fb27600  RBX: ffff88846c5da000  RCX: 000000000000001f
    RDX: 0000000000000000  RSI: 0000000000000004  RDI: 0000000000000000
    RBP: ffffffff828db1e0   R8: 00020c0bcfa85505   R9: 000000000035a8d0
    R10: 071c71c71c71c71c  R11: 0000000000000020  R12: 0000000000000002
    R13: 00020c0bcf9aeb77  R14: 00020c0bcfa85505  R15: 0000000000000000
    ORIG_RAX: ffffffffffffffdb  CS: 0010  SS: 0018
#15 [ffffc900000e7ec0] cpuidle_enter at ffffffff81a9606b
#16 [ffffc900000e7ee0] do_idle at ffffffff810cc2bf
#17 [ffffc900000e7f20] cpu_startup_entry at ffffffff810cc465
#18 [ffffc900000e7f30] start_secondary at ffffffff81080654
#19 [ffffc900000e7f50] secondary_startup_64 at ffffffff810000d4

---

PID: 0      TASK: ffff88846bd97000  CPU: 7   COMMAND: "swapper/7"
 #0 [ffffc90000234bb0] machine_kexec at ffffffff810865ff
 #1 [ffffc90000234bf8] __crash_kexec at ffffffff8110c8e7
 #2 [ffffc90000234cc0] crash_kexec at ffffffff8110d5f0
 #3 [ffffc90000234cd0] oops_end at ffffffff810651fc
 #4 [ffffc90000234cf0] page_fault at ffffffff81e0102f
    [exception RIP: qlt_handle_login+145]
    RIP: ffffffffa013a0b9  RSP: ffffc90000234da8  RFLAGS: 00010007
    RAX: ffffffffffffff90  RBX: ffff88845b2f0003  RCX: 0000000000000000
    RDX: 0000000000000000  RSI: 0000000000000046  RDI: ffff88835a6f39b0
    RBP: ffff88835a6f3598   R8: 0000000000000001   R9: 0000000000000003
    R10: ffff88835a6f3598  R11: 000000000000f026  R12: 0000000000010000
    R13: ffff88845a982c00  R14: 21000024ff422153  R15: ffff88835a6f39c0
    ORIG_RAX: ffffffffffffffff  CS: 0010  SS: 0018
 #5 [ffffc90000234df8] qlt_handle_imm_notify at ffffffffa013ad7d [qla2xxx_scst]
 #6 [ffffc90000234e68] qlt_24xx_atio_pkt at ffffffffa013b653 [qla2xxx_scst]
 #7 [ffffc90000234eb8] qlt_24xx_process_atio_queue at ffffffffa013d195 [qla2xxx_scst]
 #8 [ffffc90000234f10] qla83xx_msix_atio_q at ffffffffa013d8a2 [qla2xxx_scst]
 #9 [ffffc90000234f30] __handle_irq_event_percpu at ffffffff810e2460
#10 [ffffc90000234f70] handle_irq_event_percpu at ffffffff810e2565
#11 [ffffc90000234f98] handle_irq_event at ffffffff810e25cb
#12 [ffffc90000234fb0] handle_edge_irq at ffffffff810e5eb6
#13 [ffffc90000234fc8] do_IRQ at ffffffff81e01824
--- <IRQ stack> ---
#14 [ffffc900000ffde8] ret_from_intr at ffffffff81e00a0f
    [exception RIP: cpuidle_enter_state+237]
    RIP: ffffffff81a959dc  RSP: ffffc900000ffe90  RFLAGS: 00000202
    RAX: ffff88847fde7600  RBX: ffff88846b417400  RCX: 000000000000001f
    RDX: 0000000000000000  RSI: 0000000000000007  RDI: 0000000000000000
    RBP: ffffffff828db1c0   R8: 000003b075d219c0   R9: ffff88847fddc8e0
    R10: 071c71c71c71c71c  R11: 0000000000000020  R12: 0000000000000002
    R13: 000003b075a89bf8  R14: 000003b075d219c0  R15: 0000000000000000
    ORIG_RAX: ffffffffffffffdb  CS: 0010  SS: 0018
#15 [ffffc900000ffec0] cpuidle_enter at ffffffff81a95b0b
#16 [ffffc900000ffee0] do_idle at ffffffff810cc2bf
#17 [ffffc900000fff20] cpu_startup_entry at ffffffff810cc465
#18 [ffffc900000fff30] start_secondary at ffffffff81080654
#19 [ffffc900000fff50] secondary_startup_64 at ffffffff810000d4
```

**Comment by lnocturno** [comment] 2022-06-20 21:48
Hi Aryan,

Thanks for creating a github issue and for the detailed report.
I'll try to look at the problem again as soon as I have free time.

By the way, have you tried to test this problem with the old qlogic driver?

Thanks,
Gleb.

**Comment by StorWav** [comment] 2022-11-15 00:30
I ran into the same crash issue. This seems have something to do with ```vha->unknown_atio_list``` not initialized when creating virtual target. I think the following two lines need to be added into function ```qlt_vport_create```.
```
INIT_LIST_HEAD(&vha->unknown_atio_list);
INIT_DELAYED_WORK(&vha->unknown_atio_work, qlt_unknown_atio_work_fn);
```
I tried it and don't see crash any more.

**Comment by lnocturno** [comment] 2022-11-15 09:51
Hi,

> I ran into the same crash issue. This seems have something to do with vha->unknown_atio_list not initialized when creating virtual target. I think the following two lines need to be added into function qlt_vport_create

Thank you for finding the root cause!

I've submitted the patch to the upstream, so once it's approved and merged, I'll fetch it to SCST.
https://patchwork.kernel.org/project/linux-scsi/patch/376c89a2-a9ac-bcf9-bf0f-dfe89a02fd4b@scst.dev/

Thank you again for this report!

Gleb

**Closed** 2022-12-15 13:51 UTC
